<?php

/**
 * @file
 *
 */

  /**
 * Implements hook_permission().
 */
function faxe_furniture_webshop_permission() {
  return array(
    'administer faxe webshop' => array(
      'title' => t('Administer FAXE webshop'),
      'description' => t('Perform administration tasks faxe webshop.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function faxe_furniture_webshop_menu() {
  $items = array();
  $items['admin/config/faxe_webshop'] = array(
    'title' => 'FAXE webshop',
    'description' => 'Administer FAXE webshop',
    'position' => 'left',
    'weight' => -10,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer faxe webshop'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/faxe_webshop/settings'] = array(
    'title' => 'FAXE webshop',
    'description' => 'FAXE webshop settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('faxe_webshop_order_notification_settings_form'),
    'access arguments' => array('administer faxe webshop'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/faxe_webshop/settings/settings'] = array(
    'title' => 'Settings',
    'description' => 'FAXE webshop settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('faxe_webshop_order_notification_settings_form'),
    'access arguments' => array('administer faxe webshop'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 5,
  );
  return $items;
}

/**
 * Callback for the admin messages.
 */
function faxe_webshop_order_notification_settings_form() {
  $default_admin_message = t('Hi,
      An order "[node:title]" was placed by [node:field-order-person-first-name] [node:field-order-person-last-name] ([node:field-order-person-email])
      Ordered products:
      [faxe_furniture_webshop_order:products]');
  $default_user_message = t('Hi,
      You just placed an order on the website @sitename. Here are the order details:
      [faxe_furniture_webshop_order:products]
      We will contact you as soon as possible.', array('@sitename' => variable_get('site_name')));
  $form['messages'] = array(
    '#title' => t('Email messages'),
    '#type' => 'fieldset',
    '#description' => t('Here you can customize the mails sent to the site administrator and customer, after an order is placed.'),
  );

  $site_mail = variable_get('site_mail');
  $form['messages']['faxe_furniture_webshop_admin_emails'] = array(
    '#title' => t('Administrator emails'),
    '#type' => 'textarea',
    '#description' => t('After each placed order, an email with the order details will be sent to all the addresses from the list above.
                          Please add one email address per line.'),
    '#default_value' => variable_get('faxe_furniture_webshop_admin_emails', $site_mail),
  );

  $form['messages']['faxe_furniture_webshop_admin_subject'] = array(
    '#title' => t('Subject'),
    '#type' => 'textfield',
    '#description' => t("Subject field for the administrator's email."),
    '#default_value' => variable_get('faxe_furniture_webshop_admin_subject', t('New order placed')),
  );

  $form['messages']['faxe_furniture_webshop_admin_message'] = array(
    '#title' => t('Admin email'),
    '#type' => 'textarea',
    '#description' => t('This email will be sent to the site administrator just after an order is placed.
      Please see all available tokens below. For listing the products, please use: [faxe_furniture_webshop_order:products]'),
    '#default_value' => variable_get('faxe_furniture_webshop_admin_message', $default_admin_message),
  );

  $form['messages']['faxe_furniture_webshop_user_subject'] = array(
    '#title' => t('Subject'),
    '#type' => 'textfield',
    '#description' => t("Subject field for the user's email."),
    '#default_value' => variable_get('faxe_furniture_webshop_user_subject', t('New order placed')),
  );

  $form['messages']['faxe_furniture_webshop_user_message'] = array(
    '#title' => t('User email'),
    '#type' => 'textarea',
    '#description' => t('This email will be sent to the user just after an order is placed.
      Please see all available tokens below. For listing the products, please use: [faxe_furniture_webshop_order:products]'),
    '#default_value' => variable_get('faxe_furniture_webshop_user_message', $default_user_message),
  );

  $form['messages']['tokens'] = array(
    '#theme' => 'token_tree',
    '#dialog' => true,
    '#token_types' => array('node', 'products'),
    '#global_types' => FALSE,
    '#click_insert' => TRUE,
  );

  $form['thank_you'] = array(
    '#title' => t('Thank you page'),
    '#type' => 'fieldset',
    '#description' => t('Thank you page customization.'),
  );

  $form['thank_you']['faxe_furniture_webshop_thank_you_title'] = array(
    '#title' => t('Title'),
    '#type' => 'textfield',
    '#description' => t('Thank you page title.'),
    '#default_value' => variable_get('faxe_furniture_webshop_thank_you_title', t("Thank you.")),
  );

  $form['thank_you']['faxe_furniture_webshop_thank_you_message'] = array(
    '#title' => t('Text'),
    '#type' => 'textarea',
    '#description' => t('Thank you page text.'),
    '#default_value' => variable_get('faxe_furniture_webshop_thank_you_message', t("Thank you for placing an order on our website.\nWe will contact you as soon as possible.")),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_token_info().
 */
function faxe_furniture_webshop_token_info() {
  $info = array();

  // Add any new tokens.
  $info['tokens']['faxe_furniture_webshop_order']['products'] = array(
    'name' => t('Ordered products'),
    'description' => t('Listing of ordered products.')
  );

  // Return them.
  return $info;
}


/**
 * Implements hook_tokens().
 */
function faxe_furniture_webshop_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  // The first thing that we're going to check for is the type of token - node,
  // user etc...
  if ($type == 'faxe_furniture_webshop_order') {
    // Loop through each of the available tokens.
    foreach ($tokens as $name => $original) {
      // Find the desired token by name
      switch ($name) {
        case 'products':
          $new = '';

          $cart = faxe_basic_cart_get_cart();

          // Building the order details.
          $i = 0;
          $products = '';
          foreach ($cart as $nid => $line_item) {
            $placering = '';
            $node = node_load($nid);
            $placering_tid = field_get_items('node', $node, 'field_furniture_stock_place');
            if ($placering_tid) {
              $placering_tid = reset($placering_tid);
              $term = taxonomy_term_load($placering_tid['tid']);
              $placering = '(' . t('Placering') . ': '. $term->name . ')';
            }
            $new .= ++$i . '. - ' . t('Varenummer') . $node->nid. ': '. $node->title . $placering . "\t" .
            $line_item['faxe_basic_cart_quantity'] . "\n";
          }

          // Add the new value into the replacements array.
          $replacements[$original] = $new;
          break;
      }
    }
  }
  // Return the replacements.
  return $replacements;
}

function faxe_furniture_webshop_preprocess_node(&$vars)  {
  if (($vars['type'] == 'faxe_furniture_product') && module_exists('faxe_basic_cart')) {
    if ($vars['view_mode'] == 'teaser'){
      $vars['content']['add_to_cart_form'] = l(t('Add to cart'), '/webshop/cart/add/' .$vars['nid'], array('attributes' => array('class' => array('button btn-add-to-cart'))));
    }
    else {
      $vars['content']['add_to_cart_form'] = drupal_get_form('faxe_basic_cart_add_to_cart_form', $vars['nid']);
    }
  }
}

/**
 * Sending emails.
 */
function faxe_furniture_webshop_send_order_notifications($order) {
  // Admin message.
  $message_html = t(variable_get('faxe_furniture_webshop_admin_message'));

  // Token data.
  $data = array('node' => $order);
  $message_html = token_replace($message_html, $data);
  // Admin mail.
  $params['admin_message'] = $message_html;
  $site_mail = variable_get('site_mail');

  $admin_emails = variable_get('faxe_furniture_webshop_admin_emails');
  if (empty ($admin_emails)) {
    // Sending mail to admin.
    $message = drupal_mail('faxe_furniture_webshop', 'admin_mail', $site_mail, language_default(), $params);
  }
  else {
    $admin_emails = explode("\n", $admin_emails);
    if (is_array($admin_emails) && !empty($admin_emails)) {
      $ok = FALSE;
      foreach ($admin_emails as $admin_email) {
        // Sending mail to each admin.
        $message = drupal_mail('faxe_furniture_webshop', 'admin_mail', $admin_email, language_default(), $params);
      }
    }
  }
  $message_html = t(variable_get('faxe_furniture_webshop_user_message'));

  // Token data.
  $data = array('node' => $order);
  $message_html = token_replace($message_html, $data);
  $params['user_message'] = $message_html;
  $subject = check_plain(variable_get('faxe_furniture_webshop_user_subject'));
  $subject = token_replace($subject, $data);
  $params['user_message_subject'] = $subject;
      // Sending mail.
  $email = field_get_items('node', $order, 'field_order_person_email');
  $email = $email[0]['value'];
  $message = drupal_mail('faxe_furniture_webshop', 'user_mail', $email, language_default(), $params);
  return TRUE;
}


/**
 * Implements hook_mail().
 */
function faxe_furniture_webshop_mail($key, &$message, $params) {
  switch ($key) {
    case 'admin_mail':
      $message['subject'] = t(check_plain(variable_get('faxe_furniture_webshop_admin_subject')));
      $message['body'][] = filter_xss($params['admin_message']);
      break;

    case 'user_mail':
      $message['subject'] = $params['user_message_subject'];//t(check_plain(variable_get('faxe_furniture_webshop_user_subject')));
      $message['body'][] = filter_xss($params['user_message']);
      break;
  }
}

