<?php
/**
 * Implements hook_search_api_alter_callback_info().
 */
function os2intra_global_search_index_item_type_search_api_alter_callback_info() {
  $callbacks['os2intra_global_search_index_item_type_alter_settings'] = array(
    'name' => t('Os2Intra global search index item type'),
    'description' => t('Os2Intra global search index item type'),
    'class' => 'SearchApiAlterAddItemTypeAlterSettings',
  );
  return $callbacks;
}